### ISSUE TITLE
Unable to wire TopicConnectionFactory Beans, since they get wrapped by LazyConnectionFactory

### ISSUE THREAD

**Issue by fasseg** [spring-cloud/spring-cloud-sleuth#1324]
Dear Spring Cloud Team, 

Since Version `2.1.0` the class `TracingConnectionFactoryBeanPostProcessor` wraps any `javax.jms.ConnectionFactory` into a `LazyConnectionFactory`.

This creates an issue when autowiring beans of type `javax.jms.TopicConnectionFactory`, since any `TopicConnectionFactory` gets wrapped in a `LazyConnectionFactory` (Check [LazyConnectionFactory:78](https://github.com/spring-cloud/spring-cloud-sleuth/blob/558900155adb1ae4a732cf450c216e2ff04a3f90/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingConnectionFactoryBeanPostProcessor.java#L78)). 

But since the `LazyConnectionFactory` is not assignable to `TopicConnectionFactory` the following exception is thrown during the wiring process:
```
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'activeMqConnectionFactory' is expected to be of type 'javax.jms.TopicConnectionFactory' but was actually of type 'org.springframework.cloud.sleuth.instrument.messaging.LazyConnectionFactory'
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1257)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 51 common frames omitted```

**Comment by marcingrzejszczak** [comment]
Isn't it a duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/1284 ?

**Comment by derTobsch** [comment]
I do not think that this is a duplicate, because it feels like the same kind of behavior but its not the same class. It feels like the same category of "bugs".

**Comment by fasseg** [comment]
Yes, as @derTobsch mentioned it's the same cause, but concerning a different interface: `TopicConnectionFactory` instead of `CaConnectionFactory` in #1284.

**Comment by chsi13** [comment]
I have another related problem. I use spring jms over AMQ (via the amq boot starter) but the connection between jms listeners and the broker doesn't happened anymore with LazyConnectionFactory wrapper. So no more messages consumption.. I have to explicitly disable JMS tracing to make it works again.

**Comment by marcingrzejszczak** [comment]
Interesting. @chsi13 do you have a sample that replicates this issue?

**Comment by chsi13** [comment]
@marcingrzejszczak The issue is closed so no need samples and further informations ? Problem solved ?

**Comment by marcingrzejszczak** [comment]
Problem is solved in the latest snapshot build.

**Comment by kiranreddykasa** [comment]
@marcingrzejszczak In whhich version will this be released ? Thanks

**Comment by marcingrzejszczak** [comment]
2.0.4 and 2.1.2

**Comment by kiranreddykasa** [comment]
@marcingrzejszczak  I upgraded to 2.1.2 and still facing the facing the below error for IBM MQ factory

`Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named ‘x’ is expected to be of type 'com.ibm.mq.jms.MQQueueConnectionFactory' but was actually of type 'org.springframework.cloud.sleuth.instrument.messaging.LazyConnectionFactory'
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.checkBeanNotOfRequiredType(DefaultListableBeanFactory.java:1676)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1654)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1217)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 66 more`

**Comment by kiranreddykasa** [comment]
Sample to replicate the issue [https://github.com/kiranreddykasa/spring-sleuth-issue-sample](url)

**Comment by kiranreddykasa** [comment]
@marcingrzejszczak  If we are auto wiring with ConnectionFactory instead of concrete implementation(IBM MQ) then there is no issue. If it is expected behviour you can close this issue.

**Comment by marcingrzejszczak** [comment]
Correct, that's the expected behavior

**Comment by rojagadeesh** [comment]
@kiranreddykasa Could you please paste the working Configuration class.  How you created ConnectionFactory using autowiring

**Comment by kiranreddykasa** [comment]
@rojagadeesh We just need to auto wire interface instead of the concrete class. Please raise question in SO.

**Comment by patanjalic** [comment]
I cannot comment for all the brokers, have tried only IBM MQ.
We may need to access MQConnectionFactory after the bean is created, especially for SSL related settings, we need to set SSLSocketFactory if MQ setup needs to authenticate based on DN.

Since the MQConnectionFactory is wrapped in LazyConnectionFactory, there is no way to access underlying MQConnectionFactory, we cant autowire it or access the delegate.

I request Spring guys to disable wrapping for MQ at https://github.com/itcabb/spring-cloud-spring-cloud-sleuth/blob/8f4d7dd8d83060ffba8c60706feed83c0c8ff4b8/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingConnectionFactoryBeanPostProcessor.java

To workaround the issue we can disable tracing for JMS. 
spring.sleuth.messaging.jms.enabled=false

**Comment by marcingrzejszczak** [comment]
For now you can disable the jms tracing as mentioned via the property and instrument your connection manually as presented in the Brave's readme https://github.com/openzipkin/brave/tree/master/instrumentation/jms

**Comment by patanjalic** [comment]
thanks @marcingrzejszczak

**Comment by XuXuanXu** [comment]
> @kiranreddykasa Could you please paste the working Configuration class. How you created ConnectionFactory using autowiring

I noticed that too，I use springboot 2.5.7, spring-cloud-sleuth-brave-3.0.4，the problem is ‘xxxJmsConnectionFactory‘’is expected to be of type 'javax.jms.ExceptionListener' but was actually of type 'org.springframework.cloud.sleuth.brave.instrument.messaging.LazyConnectionFactory'。I track where the code reported the error 

JmsAnnotationDrivenConfiguration(ObjectProvider<DestinationResolver> destinationResolver,
ObjectProvider<JtaTransactionManager> transactionManager, ObjectProvider<MessageConverter> messageConverter,
ObjectProvider<ExceptionListener> exceptionListener, JmsProperties properties) {
this.destinationResolver = destinationResolver;
this.transactionManager = transactionManager;
this.messageConverter = messageConverter;
this.exceptionListener = exceptionListener;
this.properties = properties;
}
@Bean
	@ConditionalOnMissingBean
	DefaultJmsListenerContainerFactoryConfigurer jmsListenerContainerFactoryConfigurer() {
		DefaultJmsListenerContainerFactoryConfigurer configurer = new DefaultJmsListenerContainerFactoryConfigurer();
		configurer.setDestinationResolver(this.destinationResolver.getIfUnique());
		configurer.setTransactionManager(this.transactionManager.getIfUnique());
		configurer.setMessageConverter(this.messageConverter.getIfUnique());
		**configurer.setExceptionListener(this.exceptionListener.getIfUnique());**
		configurer.setJmsProperties(this.properties);
		return configurer;
	}

**Comment by shadabbahadara** [comment]
> Correct, that's the expected behavior

If we need to use org.apache.activemq.pool.PooledConnectionFactory with sleuth, is ther any way to use it instead of LazyTopicConnectionFactory?
