### ISSUE TITLE
please don't trace Actuator endpoints in Spring Boot 2.0

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-sleuth#737]
please don't trace Actuator endpoints in Spring Boot 2.0. Right now, with `M5` and Finchley and Spring Cloud Sleuth, it's tracing the `/application/refresh` endpint in Sleuth.

**Comment by marcingrzejszczak** [comment]
Fixed in https://github.com/spring-cloud/spring-cloud-sleuth/commit/11bd578738aaf510a76f6b5e78bf78f76741c16f

**Comment by saturnism** [comment]
should this be updated to ignore /actuator/* as well?

**Comment by shakuzen** [comment]
Might want to ignore the root Actuator endpoint as well `/actuator`

**Comment by marcingrzejszczak** [comment]
care for a PR? ;)

**Comment by robertofpaf** [comment]
After upgrading to spring-boot 2.0.2 and spring-cloud Finchley.RC2 I still see actuator health endpoint traces being sent to Zipkin. Could it be because we run the actuator end points on the same port and under the application context root (so something like /player-service/actuator/health)?

This is a snippet from the application.yml:
```
server:
  port: 8704
  servlet:
    context-path: /player-service

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
```

**Comment by marcingrzejszczak** [comment]
Yeah, this is a very simple way of excluding actuator endpoints by just excluding whatever is there in `/actuator/.*`. There's an open issue for `2.1.0` to make it include context path.

**Comment by ahoffer** [comment]
> Yeah, this is a very simple way of excluding actuator endpoints by just excluding whatever is there in `/actuator/.*`. There's an open issue for `2.1.0` to make it include context path.

Can you provide an example? I include 2.16-RELEASE and set my config properties to:
```json
"management.endpoints.web-org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointProperties": {
"prefix": "management.endpoints.web",
"properties": {
"pathMapping": {},
"exposure": {
"include": [
"*"
],
"exclude": [
"/actuator/.*"
]
},
"basePath": "/actuator"
}
}
```
but httptrace continues to trace calls to the /actuator endpoints.

**Comment by marcingrzejszczak** [comment]
I don't understand what this means 

> but httptrace continues to trace calls to the /actuator endpoints.
